---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r Loaddata} 
if (!file.exists("activity.csv")) unzip("activity.zip")
data <- read.csv("activity.csv")

# Take a look at the data
head(data)
summary(data)

# Turn dates into Date
data$date <- as.Date(data$date)
```

## What is mean total number of steps taken per day?
```{r totalmean} 
# 1. Calculate the total number of steps taken per day
daysteps <- aggregate(data$steps, by = list(data$date), FUN = sum)
colnames(daysteps) <- c("Date", "Steps")
head(daysteps, 14)
```

```{r daystepsplot}
# 2. Make a histogram of the total number of steps taken each day
library(ggplot2)
m <- ggplot(daysteps, aes(x = Steps))
m + geom_histogram(fill = "red", col = "black") + 
    theme_bw() +
    labs(title = "Histogram for mean total number of steps taken per day") +
    labs(x = "Steps per day", y = "Count")
```

```{r meanmedian}
# 3. Calculate and report the mean and median of the total number of steps taken per day
meansteps <- mean(daysteps$Steps, na.rm = TRUE)
meansteps
mediansteps <- median(daysteps$Steps, na.rm = TRUE)
mediansteps
```

## What is the average daily activity pattern?
```{r dailypattern}
# 1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
intervalsteps <- aggregate(data$steps, by = list(data$interval), FUN = mean, na.rm=TRUE)
colnames(intervalsteps) <- c("Interval", "Steps")
plot(intervalsteps, type = "l")
```

## Imputing missing values
```{r NAs}
# 1. Calculate and report the total number of missing values in the dataset 
countna <- sum(is.na(data))
print(paste0("There are ", countna, " missing values (NAs) in the dataset"))
```

```{r NAstrategy}
# 2. Devise a strategy for filling in all of the missing values in the dataset
# I decided to use the mean value per 5min interval for each day to have higher accuracy.
data$weekday <- format(data$date, format = "%A")
dayinterval <- aggregate(data$steps, by = list(data$interval, data$weekday), FUN = mean, na.rm=TRUE)
colnames(dayinterval) <- c("interval", "weekday", "meansteps")
newdata <- merge(data, dayinterval, by = c("interval", "weekday"))
newdata <- newdata[order(newdata$date, newdata$interval), ]

# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in
newdata$steps[is.na(newdata$steps)] <- newdata$meansteps[is.na(newdata$steps)] # Fill in missing values
newdata <- newdata[, c("steps", "date", "interval")] # Subset newdata to match the columns of the original dataset
```

```{r noNAplot}
# 4. Make a histogram of the total number of steps taken each day 
newdaysteps <- aggregate(newdata$steps, by = list(newdata$date), FUN = sum)
colnames(newdaysteps) <- c("Date", "Steps")

library(ggplot2)
m <- ggplot(newdaysteps, aes(x = Steps))
m + geom_histogram(fill = "red", col = "black") + 
    theme_bw() +
    labs(title = "Histogram for mean total number of steps taken per day") +
    labs(x = "Steps per day", y = "Count")

# Calculate and report the mean and median total number of steps taken per day.
newmeansteps <- mean(newdaysteps$Steps, na.rm = TRUE)
newmeansteps

newmediansteps <- median(newdaysteps$Steps, na.rm = TRUE)
newmediansteps

#Do these values differ from the estimates from the first part of the assignment?
print(paste0("The mean of ", newmeansteps, " is ", newmeansteps - meansteps, " higher than the old dataset"))
print(paste0("The median of ", newmediansteps, " is ", newmediansteps - mediansteps, " higher than the old dataset"))

# It seems that inputting missing data results in higher frequencies on the histogram as well as higher values
```

## Are there differences in activity patterns between weekdays and weekends?
```{r weekendactivities}
# 1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
weekend <- function(day) {
  if (day %in% c("Saturday", "Sunday")) {
    "Weekend"
  } else {
    "Weekday"
  }
}

newdata$weekday <- format(newdata$date, format = "%A")
newdata$daytype <- as.factor(sapply(newdata$weekday, weekend))

weekenddata <- aggregate(newdata$steps, by = list(newdata$daytype, newdata$interval), FUN = mean)
colnames(weekenddata) <- c("daytype", "interval", "steps")

m <- ggplot(weekenddata, aes(interval, steps))
m + facet_grid(daytype ~ .) +
    geom_line()
```
